title: "Little-known and abandoned airfields in the DRC"
description: "A documentation project for airports and airstrips in the Democratic Republic of the Congo."
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
highlighter: rouge
header_pages:
  - index.md
  - list.md
  - map.md
sass:
  style: compressed
  load_paths:
    - _sass
