title: "Little-known and abandoned airfields in the DRC"
description: "A documentation project for airports and airstrips in the Democratic Republic of the Congo."
theme: null
plugins:
  - jekyll-feed
markdown: kramdown
highlighter: rouge
include:
  - styles/style.css
header_pages:
  - index.md
  - list.md
  - map.md
