title: "Little-known and abandoned airfields in the DRC"
description: "A documentation project for airports and airstrips in the Democratic Republic of the Congo."
theme: null
include:
  - _layouts
  - _includes
  - _sass
  - assets
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-robots-txt
header_pages:
  - index.md
  - list.md
  - map.md
defaults:
  - scope:
      path: "_layouts"
    values:
      sitemap: false
  - scope:
      path: "_includes"
    values:
      sitemap: false
  - scope:
      path: "assets"
    values:
      sitemap: false
  - scope:
      path: "_sass/minima/"
    values:
      sitemap: false
sitemap:
  include_xml_header: true
markdown: kramdown
highlighter: rouge
